on: [push]

jobs:
  create_release:
    runs-on: ubuntu-latest
    container:
      image: debian:buster
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create release
        run: hub release create -m "$(date)" "v$(date +%s)"
